---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  name: gitea
  namespace: gitea
spec:
  giteaSsl: true
  giteaVolumeSize: 4Gi
  postgresqlVolumeSize: 4Gi
  giteaAdminUser: opentlc-mgr
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaAdminPasswordLength: 32
