---
# Source: showroom-single-pod/templates/terminal/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: showroom-factory
  namespace: showroom-factory
---
# Source: showroom-single-pod/templates/proxy/configmap-traefik-dynamic.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: showroom-factory-traefik-dynamic
  namespace: showroom-factory
data:
  dynamic.yml: |
    http:
      routers:
        showroom:
          rule: "PathPrefix(`/`)"
          entryPoints:
            - web
          service: showroom
          priority: 1
        terminal:
          rule: "PathPrefix(`/terminal`)"
          entryPoints:
            - web
          service: terminal
          middlewares:
            - terminal-stripprefix
          priority: 10
        wetty:
          rule: "PathPrefix(`/wetty`)"
          entryPoints:
            - web
          service: wetty
          priority: 10

      services:
        showroom:
          loadBalancer:
            servers:
              - url: "http://127.0.0.1:8000"
        terminal:
          loadBalancer:
            servers:
              - url: "http://127.0.0.1:7681"
        wetty:
          loadBalancer:
            servers:
              - url: "http://127.0.0.1:8001"
      middlewares:
        terminal-stripprefix:
          stripPrefix:
            prefixes:
              - "/terminal"
---
# Source: showroom-single-pod/templates/proxy/configmap-traefik-static.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: showroom-factory-traefik-static
  namespace: showroom-factory
data:
  traefik.yml: |
    api:
      dashboard: false
      insecure: false
    entryPoints:
      web:
        address: ":8080"
    ping:
      entryPoint: web
    providers:
      file:
        filename: /etc/traefik/dynamic.yml
        watch: false
    log:
      level: INFO
    accessLog: {}
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
---
# Source: showroom-single-pod/templates/proxy/configmap-user-data.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: showroom-factory-userdata
  namespace: showroom-factory
data:
  user_data.yml: |
    user: user1
    password: "<workshop password>"
    openshift_console_url: https://console-openshift-console.apps.salamander.aimlworkbench.com
    openshift_api_url: https://api.salamander.aimlworkbench.com:6443
    devhub_url: https://v1-developer-hub-rhdh-test.apps.salamander.aimlworkbench.com
    gitops_url: https://openshift-gitops-server-openshift-gitops.apps.salamander.aimlworkbench.com
    mattermost_url: https://mattermost-mattermost.apps.salamander.aimlworkbench.com
    ocp_version: "4.21"
---
# Source: showroom-single-pod/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: showroom-factory-terminal-lab-user-home
  namespace: showroom-factory
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
---
# Source: showroom-single-pod/templates/terminal/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-showroom-factory-sa
  namespace: showroom-factory
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: showroom-factory
  namespace: showroom-factory
---
# Source: showroom-single-pod/templates/proxy/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showroom-factory
  namespace: showroom-factory
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: showroom-factory
---
# Source: showroom-single-pod/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showroom-factory
  namespace: showroom-factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: showroom-factory
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: showroom-factory
      annotations:
        checksum/traefik-static: a8de5299f7b2966e2852965185fbb2d4ffb2cc45860a59c4d61cac3b9e13214b
        checksum/traefik-dynamic: a02b0cc4b3df4346cc2c3a3fac2523acc477f0837e34b329349c36815722dec3
        checksum/userdata: 26bb9f7c2651a5737ef2c053c8806b5def0ec4e4f85135c1300fad5f7b649030
    spec:
      serviceAccountName: showroom-factory
      initContainers:
      - name: git-cloner
        image: "quay.io/rhpds/git-cloner:v1.1.5"
        env:
        - name: GIT_REPO_URL
          value: "https://github.com/enterprisewebservice/showroom-openshift-software-factory.git"
        - name: GIT_REPO_REF
          value: "main"
        - name: CLONE_DIR
          value: "/showroom/repo"
        volumeMounts:
        - mountPath: /showroom/repo
          name: showroom-factory-files
          subPath: repo
      - name: antora-builder
        image: "quay.io/rhpds/antora:v1.3.0"
        env:
        - name: FILES_DIR
          value: "/showroom/repo"
        - name: OUTPUT_DIR
          value: "/showroom/www"
        - name: ANTORA_SITE_FILE
          value: "site.yml"
        - name: ANTORA_ENABLE_DEV_MODE
          value: "false"
        volumeMounts:
        - mountPath: /showroom/repo
          name: showroom-factory-files
          subPath: repo
        - name: user-data
          mountPath: /user_data/
        - mountPath: /showroom/www
          name: showroom-factory-files
          subPath: www
      containers:
      - name: traefik
        image: "quay.io/rhpds/traefik:v3.7.9"
        imagePullPolicy: "IfNotPresent"
        args:
        - "--configFile=/etc/traefik/traefik.yml"
        volumeMounts:
        - mountPath: /etc/traefik/traefik.yml
          name: traefik-static
          subPath: traefik.yml
          readOnly: true
        - mountPath: /etc/traefik/dynamic.yml
          name: traefik-dynamic
          subPath: dynamic.yml
          readOnly: true
        ports:
        - name: web
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 5m
            memory: 16Mi

      - name: content
        image: "quay.io/rhpds/showroom-content:v1.4.2"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: GIT_REPO_URL
          value: "https://github.com/enterprisewebservice/showroom-openshift-software-factory.git"
        - name: GIT_REPO_REF
          value: "main"
        - name: ANTORA_PLAYBOOK
          value: "site.yml"
        - name: ZT_BUNDLE
          value: "https://github.com/rhpds/nookbag/releases/download/nookbag-v0.4.0/nookbag-v0.4.0.zip"
        - name: ZT_UI_ENABLED
          value: "true"
        - name: SHOWROOM_UI_CONFIG
          value: ""
        - name: DOMAIN
          value: "apps.salamander.aimlworkbench.com"
        - name: GUID
          value: "dev01"
        - name: USER
          value: "dean"
        volumeMounts:
        - name: user-data
          mountPath: /user_data/
        - mountPath: /showroom/repo
          name: showroom-factory-files
          subPath: repo
        - mountPath: /showroom/www
          name: showroom-factory-files
          subPath: www
        ports:
        - containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      - name: terminal
        image: "quay.io/rhpds/openshift-showroom-terminal-ocp:latest"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GUID
          value: "dev01"
        volumeMounts:
        - name: terminal-lab-user-home
          mountPath: /home/lab-user
        - name: terminal-data-ssh # to enable ssh out of the container
          mountPath: /data/.ssh
        ports:
        - containerPort: 7681
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      - name: wetty
        image: "quay.io/rhpds/wetty:v3.2.1"
        imagePullPolicy: "IfNotPresent"
        args:
        - --base="/wetty/"
        - --port=8001
        - --allow-iframe=true
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GUID
          value: "dev01"
        ports:
        - containerPort: 8001
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi

      volumes:
      - name: showroom-factory-files
        emptyDir: {}
      - name: user-data
        configMap:
          name: showroom-factory-userdata
      - name: traefik-static
        configMap:
          name: showroom-factory-traefik-static
      - name: traefik-dynamic
        configMap:
          name: showroom-factory-traefik-dynamic
      - name: terminal-data-ssh # to enable ssh out of the container
        emptyDir: {}
      - name: terminal-lab-user-home
        persistentVolumeClaim:
          claimName: showroom-factory-terminal-lab-user-home
---
# Source: showroom-single-pod/templates/proxy/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: showroom-factory
  namespace: showroom-factory
  annotations:
    haproxy.router.openshift.io/timeout: 1h
    haproxy.router.openshift.io/timeout-tunnel: 1h
spec:
  to:
    kind: Service
    name: showroom-factory
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
